apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {% comment %} The selector in the Service is a set of key-value pairs that determine which Pods should receive traffic from the Service.
  In this case, the Service will route traffic to Pods with the label app set to the value of {{ .Values.name }}. {% endcomment %}
  selector:
    app: {{ .Values.name }}
