name: bff
replicaCount: 1
container:
  image:
    repository: keigokida/gomicroservices
    tag: bff
    pullPolicy: Always
  dns:
    query: query-service
    command: command-service

service:
  type: NodePort
  port: 8080
  queryPort: 8081
  commandPort: 8082
