name: query-service
replicaCount: 1
container:
  image:
    repository: keigokida/gomicroservices
    tag: query_service
    pullPolicy: Always
  dns:
    query: query-service
    command: command-service

service:
  type: ClusterIP
  port: 8081
  queryPort: 8081
  commandPort: 8082
