# Default values for microservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: microservice
replicaCount: 1
container:
  image:
    # DockerHub Repository
    repository: keigokida/gomicroservices
    tag: microservice
    pullPolicy: IfNotPresent
  dns:
    query: query-service
    command: command-service

service:
  type: ClusterIP
  port: 8080
  queryPort: 8081
  commandPort: 8082

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: microservice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

